[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install yt-dlp --target ./vendor/python",
  "PYTHONPATH=./vendor/python python3 -m yt_dlp --version"
]

[start]
cmd = "npm start"