[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "python -m pip install yt-dlp --target ./vendor/python",
  "mkdir -p ./bin",
  "cp ./vendor/python/bin/yt-dlp ./bin/yt-dlp",
  "chmod +x ./bin/yt-dlp",
  "./bin/yt-dlp --version"
]

[start]
cmd = "npm start"